version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore LtiLibrary.NetCore.sln
build:
  project: LtiLibrary.NetCore.sln
  verbosity: minimal
test_script:
- cmd: >-
    dotnet test test\LtiLibrary.NetCore.Tests\LtiLibrary.NetCore.Tests.csproj

    dotnet test test\LtiLibrary.AspNetCore.Tests\LtiLibrary.AspNetCore.Tests.csproj
deploy:
  release: LtiLibrary-v$(appveyor_repo_tag_name)
  description: 'LtiLibrary GitHub Release'
  provider: GitHub
  draft: false
  prerelease: false
  auth_token:
    secure: 8qBVDGesDnedmh5+DkAu3Gz959MjOaBhb9v3wehLrC3urdhIxLJqPzhxqxiGt2QH
  on:
    branch: master
    appveyor_repo_tag: true